
	/control/verbose 0
	/run/verbose 0
	/event/verbose 0
	
	/mydet/generator fGParticleSource
	/gps/particle e-
	/gps/energy 100 GeV
		#/gps/source/clear
		#/gps/source/add 1
	/gps/direction 0 0 1
		
	# 设置高斯分布
	/gps/pos/type Beam
	/gps/pos/shape Ellipse
	# /gps/pos/radius 10 cm
	# /gps/pos/sigma_r 2. cm
	/gps/pos/centre -0.1846 0.7962  -60. cm
	/gps/pos/sigma_x 1.2954 cm
	/gps/pos/sigma_y 0.9838 cm

	/run/beamOn 5000

	
